import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <nav className='px-5 py-3 flex justify-between'>
                    <Link href='/'>Home</Link>

                    <div className='space-x-3'>
                        <Link href='/login'>Login</Link>
                        <Link href='/login'>Register</Link>
                    </div>
                </nav>

                {children}
            </body>
        </html>
    );
}
